const fakeApi = [
  {
    Title: "Ms. Marvel",
    Year: "2022",
    Rated: "TV-PG",
    Released: "08 Jun 2022",
    Runtime: "N/A",
    Genre: "Action, Adventure, Comedy",
    Director: "N/A",
    Writer: "Bisha K. Ali",
    Actors: "Iman Vellani, Matt Lintz, Zenobia Shroff",
    Plot: "Kamala, a superhero fan with an imagination--particularly when it comes to Captain Marvel--feels like she doesn't fit in at school and sometimes even at home, that is until she gets superpowers like the heroes she admires.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 3 Primetime Emmys. 7 wins & 14 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmQ3OTZkNDUtNTU0Mi00ZjE4LTgyNTUtY2E4NWRmNDUxMzkyXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "6.3/10" }],
    Metascore: "N/A",
    imdbRating: "6.3",
    imdbVotes: "113,979",
    imdbID: "tt10857164",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Captain Marvel",
    Year: "2019",
    Rated: "PG-13",
    Released: "08 Mar 2019",
    Runtime: "123 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Anna Boden, Ryan Fleck",
    Writer: "Anna Boden, Ryan Fleck, Geneva Robertson-Dworet",
    Actors: "Brie Larson, Samuel L. Jackson, Ben Mendelsohn",
    Plot: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    Language: "English",
    Country: "United States, Australia",
    Awards: "10 wins & 57 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.8/10" },
      { Source: "Rotten Tomatoes", Value: "79%" },
      { Source: "Metacritic", Value: "64/100" },
    ],
    Metascore: "64",
    imdbRating: "6.8",
    imdbVotes: "594,177",
    imdbID: "tt4154664",
    Type: "movie",
    DVD: "28 May 2019",
    BoxOffice: "$426,829,839",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
export default fakeApi;
